### ISSUE TITLE
Start

### ISSUE THREAD

**Issue by adrianodemoura** [murilolopes/adminLTE#1]
Acredito que seja necessário arrumar a estrutura de arquivos e diretórios, seria interessante colocarmos o template num plugin, assim ele pode ser replicado melhor.

**Comment by murilolopes** [comment]
@adrianodemoura, desculpa o sumiço :s você fala em deixar tudo no plugin e só fazer chamadas no app, em ter que mover arquivos do plugin para a pasta do app? Se for isso eu pensei assim também, porem não achei conteúdo sobre isso :/
