### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by koffisani** [murilolopes/adminLTE#4]
With CakePHP 3.2.*
I run this : 

```
composer require murilolopes/adminlte:dev-master
```

And got this message : 

> Installation failed, reverting ./composer.json to its original content.
> 
> [RuntimeException]
>   Unable to get primary namespace for package murilolopes/adminlte.
>   Ensure you have added proper 'autoload' section to your plugin's config as
>   stated in README on https://github.com/cakephp/plugin-installer

How to fix this ?

**Comment by murilolopes** [comment]
@koffisani thanks for report this bug, i will try to solve.
